server {

    listen 443 ssl;

    server_name hrami.42.fr;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate     /etc/ssl/certs/nginx.crt;
    ssl_certificate_key /etc/ssl/private/nginx.key;

    root /var/www/html;

    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /static/ {
        proxy_pass http://static;
    }

    location /netdata/ {
        proxy_pass http://netdata:19999/;
    }
    
    location = /adminer {
        return 301 /adminer/index.php;
    }

    location /adminer {
        alias /var/www/html/adminer/;
        index index.php;
    }

    location ~ ^/adminer/.*\.php$ {
        alias /var/www/html/adminer/;

        include fastcgi_params;
        fastcgi_pass adminer:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html/adminer/index.php;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
    
}
